### ISSUE TITLE
def syntax

### ISSUE THREAD

**Issue by xbsd** [gcarq/keras-timeseries-prediction#1]
Is the inadvertent (->, etc) in the defs ?
It ran fine when I fixed the defs, but was curious what you did to run it the way it was done in the examples. Thanks
def load_dataset(datasource: str) -> (numpy.ndarray, MinMaxScaler):`

**Comment by gcarq** [comment]
Those are python typehints, they are supported with python3.6+: https://docs.python.org/3/library/typing.html

Unfortunately older interpreters fail when using typehints

**Comment by xbsd** [comment]
Thanks !
